const ROUTE_DETAILS={
  "d1-naniwa-lunch":{"kind":"도보","title":"난카이 난바역 → 닛폰바시역 10번 출구 옆 식당","steps":["숙소 짐 보관 후 센니치마에 거리를 동쪽 닛폰바시역 방향으로 이동. 난바역에서 도보 약 10~15분 추정, 숙소 경유는 별도.","닛폰바시역 10번 출구 옆 日本橋丸中ビル 1층 浪速日本橋食堂 도착.","식사 후 구로몬시장 북서쪽 입구로 도보 약 2~5분."],"tip":"14:15까지 식사가 어렵다면 식당을 생략하고 시장부터 방문.","origin":"Nankai Namba Station","destination":"浪速日本橋食堂 大阪府大阪市中央区日本橋1-17-20"},
  "d1p1": {"kind":"전철","title":"간사이공항 → 난카이 난바역","steps":["KIX 제1터미널 입국장 2층 연결 통로를 따라 간사이공항역(関西空港駅) 난카이 개찰구로 이동.","난카이 공항선 라피트(지정석 별도권) 또는 공항급행을 타고 난카이 난바역(南海なんば駅) 종점에서 하차.","난카이 난바역에서 숙소 방향 출구를 확인. 숙소 위치가 아직 없으므로 역 이후 이동은 별도 길찾기."],"tip":"JR 간사이공항역과 난카이 간사이공항역은 같은 공항 철도 건물에 있지만 개찰구가 다름.","origin":"Kansai-Airport Station Nankai","destination":"Nankai Namba Station"},
  "d1p2": {"kind":"도보","title":"난카이 난바역 → 구로몬시장","steps":["난카이 난바역 북쪽/난바 중심부로 나와 닛폰바시(日本橋)·구로몬시장 표지를 따라 동쪽으로 이동.","센니치마에 거리에서 닛폰바시 2초메 쪽으로 가서 구로몬시장 서쪽 입구로 진입. 지하철을 타면 오사카 메트로 난바역 → 닛폰바시역(센니치마에선, 1정거장) 후 10번 출구 부근."],"origin":"Nankai Namba Station","destination":"Kuromon Ichiba Market"},
  "d1-yasaka": {"kind":"도보","title":"구로몬시장 → 난바 야사카 신사","steps":["구로몬시장 서쪽 입구로 돌아와 난카이 난바역 쪽으로 서쪽 이동.","난카이 난바역 남쪽을 지나 난바나카(難波中) 방향으로 내려가 난바 야사카 신사 정문으로 이동."],"tip":"구로몬시장의 어느 점포에서 출발하는지에 따라 거리 차이 있음.","origin":"Kuromon Ichiba Market","destination":"Namba Yasaka Shrine"},
  "d1p4": {"kind":"도보","title":"난바 야사카 신사 → 호젠지","steps":["신사에서 북쪽 난카이 난바역·난바시티 방향으로 이동.","센니치마에 상점가를 지나 호젠지 요코초 표지를 찾아 골목으로 진입. 호젠지는 도톤보리 남쪽."],"origin":"Namba Yasaka Shrine","destination":"Hozenji Temple Osaka"},
  "d1p5": {"kind":"도보","title":"호젠지 → 도톤보리 에비스바시","steps":["호젠지 요코초에서 북쪽 도톤보리 강변으로 이동.","글리코 간판 앞 에비스바시(戎橋) 쪽으로 서쪽 이동해 저녁 동선을 시작."],"origin":"Hozenji Temple Osaka","destination":"Ebisubashi Bridge Dotonbori"},
  "d1p6": {"kind":"도보","title":"도톤보리 → 신사이바시스지","steps":["에비스바시를 북쪽으로 건너 에비스바시스지·신사이바시스지 아케이드를 따라 직진.","다이마루 신사이바시점·오사카 메트로 신사이바시역 주변에서 종료. 숙소 복귀는 숙소 위치에 맞춰 선택."],"origin":"Ebisubashi Bridge Dotonbori","destination":"Shinsaibashi-suji Shopping Street"},
  "d2p1": {"kind":"지하철 + 도보","title":"난바역 → 도부쓰엔마에역 → 쓰텐카쿠","steps":["오사카 메트로 난바역(M20)에서 미도스지선 덴노지·나카모즈 방면 승차.","도부쓰엔마에역(M22)에서 하차(다이코쿠초역 다음); 1번 출구·신세카이 방면으로 이동.","잔잔요코초·신세카이 거리를 따라 쓰텐카쿠 1층 티켓센터까지 도보."],"tip":"숙소 출발역이 난카이 난바역이면 메트로 난바역까지 지하 연결 통로 이동이 추가됨.","origin":"Osaka Metro Namba Station","destination":"Tsutenkaku"},
  "d2-walk-shitennoji": {"kind":"도보","title":"쓰텐카쿠 → 시텐노지 서문","steps":["쓰텐카쿠에서 덴노지 동물원 북쪽의 에비스히가시를 지나 북동쪽으로 이동.","마쓰야마치스지를 따라 북상하여 시텐노지 서대문(石鳥居·西大門) 쪽으로 진입."],"origin":"Tsutenkaku","destination":"Shitennoji Temple west gate"},
  "d2-shitennoji": {"kind":"경내 도보","title":"시텐노지 서문 → 중심가람","steps":["서대문에서 경내 안쪽 중심가람 입구를 찾아 입장권·주유패스 대상 구역을 확인.","중심가람 관람 후 북서쪽 시텐노지마에유히가오카역 방면으로 이동할 준비."],"origin":"Shitennoji Temple west gate","destination":"Shitennoji Temple"},
  "d2-to-castle": {"kind":"지하철 + 도보","title":"시텐노지마에유히가오카역 → 다니마치욘초메역 → 오사카성","steps":["시텐노지 서쪽에서 북쪽으로 걸어 오사카 메트로 시텐노지마에유히가오카역(T26)으로 이동.","다니마치선 다이니치 방면 승차, 다니마치욘초메역(T23) 하차(다니마치큐초메·다니마치로쿠초메 다음). 환승 없음.","9번 출구 쪽으로 나와 바바초·오테몬 방향으로 걸어 오사카성 공원 진입 → 오테몬·사쿠라몬을 지나 천수각."],"tip":"하차역부터 천수각까지 공원 내 보행이 길어 40분 이동칸은 빠듯할 수 있음.","origin":"Shitennoji-mae Yuhigaoka Station","destination":"Osaka Castle Main Tower"},
  "d2p2": {"kind":"경내 도보","title":"오사카성 천수각 → 사쿠라몬·오테몬","steps":["천수각 본마루에서 내려와 사쿠라몬을 거쳐 서쪽 오테몬으로 이동.","오테몬 밖 오테마에 식당가와 역사박물관 쪽으로 나올 수 있도록 서쪽 출구 사용."],"origin":"Osaka Castle Main Tower","destination":"Otemon Gate Osaka Castle"},
  "d2-lunch": {"kind":"도보","title":"오사카성 오테몬 → 오테마에·역사박물관","steps":["오테몬을 나와 서쪽 오테마에 거리·오사카부청 앞을 따라 이동.","오사카 역사박물관(다니마치욘초메역 9번 출구 바로 옆) 근처에서 식사 후 박물관으로 이동."],"tip":"원래 50분 칸에 걷기와 점심이 모두 포함되므로 대기가 길면 박물관 관람을 줄여야 함.","origin":"Otemon Gate Osaka Castle","destination":"Osaka Museum of History"},
  "d2-museum": {"kind":"박물관 내 이동","title":"오사카 역사박물관 입구 → 상설전시","steps":["오테마에 거리의 박물관 입구로 진입. 가까운 지하철역은 다니마치욘초메역(T23/C18), 9번 출구.","상설전시 관람 후 같은 출입구로 나와 지하철 다니마치선 개찰구로 이동."],"origin":"Osaka Museum of History","destination":"Tanimachi 4-chome Station"},
  "d2-to-umeda": {"kind":"지하철 + 도보","title":"다니마치욘초메역 → 히가시우메다역 → 스카이빌딩","steps":["역사박물관 앞 다니마치욘초메역(T23)에서 다니마치선 다이니치 방면 승차.","히가시우메다역(T20) 하차(덴마바시·미나미모리마치 다음). 환승 없이 중앙 개찰구에서 JR 오사카역·그랜드프런트 오사카 안내를 따라 서쪽 이동.","오사카역 북쪽 우메키타 광장 쪽으로 나와 스카이빌딩·공중정원 표지를 따라 도보 이동."],"tip":"히가시우메다역에서 빌딩까지 역내 통로와 지상 보행이 길다. 횡단보도·공사 동선은 현장 표지 우선.","origin":"Tanimachi 4-chome Station","destination":"Umeda Sky Building"},
  "d2-sky-entry": {"kind":"건물 내 이동","title":"우메다 스카이빌딩 1층 → 공중정원 접수","steps":["스카이빌딩 사이의 공중정원(空中庭園展望台) 입구 표지를 찾아 입장 동선으로 이동.","엘리베이터·에스컬레이터를 따라 39층 티켓 카운터로 올라가 입장 준비."],"origin":"Umeda Sky Building","destination":"Kuchu Teien Observatory"},
  "d2p4": {"kind":"관람·복귀","title":"공중정원 → 숙소 방향","steps":["공중정원 관람 뒤 같은 동선으로 스카이빌딩 1층까지 내려옴.","난바 숙소 복귀 시 JR 오사카역 남쪽 오사카 메트로 우메다역(M16)까지 걸어가 미도스지선 나카모즈 방면 → 난바역(M20) 하차."],"tip":"이날 마지막 일정 뒤 복귀편을 함께 표기했으며 숙소 정확한 위치에 맞춰 최종 도보를 확인.","origin":"Umeda Sky Building","destination":"Osaka Metro Namba Station"},
  "d3p1": {"kind":"지하철 + 게이한 + 도보","title":"오사카 메트로 난바역 → 요도야바시역 → 기요미즈고조역 → 청수사","steps":["오사카 메트로 난바역(M20)에서 미도스지선 신오사카·미노오카야노 방면 → 요도야바시역(M17) 하차. 게이한 요도야바시역(KH01) 연결 통로로 이동.","게이한 본선에서 데마치야나기 방면 승차. 기요미즈고조역(KH38)에는 보통·준급만 정차하므로 특급 승차 시 단바바시역(KH30)에서 보통/준급으로 갈아타고 기요미즈고조역에서 하차.","기요미즈고조역 4번 출구 → 고조도리 동쪽 → 고조자카 오르막 → 청수사 니오몬. 역에서 약 25분 도보."],"tip":"05:30 출발·07:00 입장은 첫차와 환승 대기, 언덕 도보를 감안하면 빠듯함. 출발 1주 전 11/27 실제 첫차를 조회하고 더 늦게 도착할 수 있음을 감안.","origin":"Osaka Metro Namba Station","destination":"Kiyomizu-dera"},
  "d3p2": {"kind":"경내 도보","title":"청수사 니오몬 → 본당 → 산넨자카","steps":["니오몬·사이몬을 지나 본당 입장, 무대·오토와 폭포를 관람.","출구에서 기요미즈자카를 따라 내려와 산넨자카(三年坂) 갈림길에서 다음 일정 시작."],"origin":"Kiyomizu-dera","destination":"Sannenzaka"},
  "d3p3": {"kind":"도보","title":"산넨자카 → 니넨자카 → 야사카노토","steps":["청수사 아래 기요미즈자카에서 산넨자카 계단을 내려감.","니넨자카 골목을 따라 북쪽으로 걸어 야사카노토(호칸지 오층탑) 앞에 도착.","고다이지로 갈 경우 네네노미치 방면으로 북쪽 이동."],"origin":"Sannenzaka Kyoto","destination":"Yasaka Pagoda"},
  "d3p4": {"kind":"도보 · 선택","title":"야사카노토 → 고다이지 → 기온","steps":["야사카노토에서 북쪽 네네노미치를 따라 고다이지 입구까지 도보.","관람 뒤 야사카 신사 남쪽을 지나 시조도리·기온 하나미코지 쪽으로 이동. 고다이지를 생략해도 같은 골목 방향으로 직행."],"origin":"Yasaka Pagoda","destination":"Kodai-ji"},
  "d3p5": {"kind":"도보","title":"고다이지 방면 → 기온 하나미코지","steps":["고다이지·네네노미치에서 야사카 신사 남쪽을 지나 시조도리로 이동.","시조도리에서 하나미코지 입구로 들어가 기온 산책. 다음 철도 승차역은 게이한 기온시조역(KH39)."],"origin":"Kodai-ji","destination":"Hanamikoji Street Kyoto"},
  "d3p6": {"kind":"게이한 + 지하철 + 도보","title":"기온시조역 → 산조역·산조케이한역 → 게아게역 → 난젠지","steps":["하나미코지 북쪽 시조도리에서 서쪽으로 게이한 기온시조역(KH39)으로 이동.","게이한 본선 데마치야나기 방면으로 한 정거장 → 산조역(KH40) 하차. 지하 연결 통로로 교토시영 지하철 산조케이한역(T11) 환승.","도자이선 로쿠지조·비와코하마오쓰 방면으로 2정거장 → 게아게역(T09) 하차. 난젠지·수로각 안내를 따라 도보 약 10~15분."],"tip":"점심은 기온 구간 뒤 확보. 게아게역 출구는 현장 난젠지 안내 표지를 따름.","origin":"Gion-Shijo Station","destination":"Nanzen-ji"},
  "d3p7": {"kind":"도보","title":"난젠지 수로각 → 에이칸도","steps":["난젠지 수로각에서 삼문·북쪽 출입구 방향으로 걸어 나옴.","가노시타치우리 쪽으로 북상해 에이칸도(젠린지) 입구로 진입. 지하철 탑승 없음."],"origin":"Nanzen-ji Suirokaku","destination":"Eikando Temple"},
  "d3p8": {"kind":"지하철 + 게이한 + 도보","title":"에이칸도 → 청수사 야간관람 → 난바 복귀","steps":["에이칸도에서 남쪽 게아게역(T09)까지 걷고 도자이선 우즈마사텐진가와 방면 → 산조케이한역(T11) 하차.","게이한 산조역(KH40)으로 갈아타 요도야바시 방면 보통/준급 → 기요미즈고조역(KH38) 하차. 4번 출구 → 고조자카로 청수사까지 약 25분 오르막 도보.","야간관람 후 기요미즈고조역으로 내려와 게이한 요도야바시 방면 보통/준급 승차. 중간에 더 빠른 특급으로 바꾸려면 단바바시역 등 정차역에서 갈아타고 요도야바시역(KH01) 하차 → 오사카 메트로 미도스지선 난바역(M20)."],"tip":"에이칸도에서 16:30 출발 뒤 18:00 청수사 입장까지 이동·저녁 시간이 빠듯할 수 있음. 4명 택시 이용 시 목적지 ‘청수사 고조자카’로 요청해 현장 교통통제 확인.","origin":"Eikando Temple","destination":"Kiyomizu-dera"},
  "d4p1": {"kind":"긴테쓰","title":"오사카난바역 → 긴테쓰나라역","steps":["난카이 난바역/메트로 난바역과 구분해 긴테쓰 오사카난바역(A01) 개찰구로 이동.","긴테쓰 나라선 긴테쓰나라행 쾌속급행 또는 급행을 타고 긴테쓰나라역(A28) 종점 하차. 열차 행선지가 야마토사이다이지까지만이면 거기서 나라행으로 환승."],"tip":"추가 요금이 드는 긴테쓰 특급을 선택할 필요는 없음. 토요일 시간표를 직전 확인.","origin":"Osaka-Namba Station Kintetsu","destination":"Kintetsu-Nara Station"},
  "d4p2": {"kind":"역내 이동","title":"긴테쓰나라역 개찰구 → 코인로커 → 공원 방향 출구","steps":["긴테쓰나라역 지하 개찰구를 나온 후 역 구내 ‘Coin Lockers/コインロッカー’ 표지에서 짐 보관.","히가시무키 상점가가 아닌 나라공원·현청(県庁) 방면 1번 출구를 기준으로 지상 이동."],"tip":"큰 짐 로커가 없으면 역내 유인 보관소 운영 시간 확인.","origin":"Kintetsu-Nara Station","destination":"Kintetsu Nara Station Exit 1"},
  "d4p3": {"kind":"도보","title":"긴테쓰나라역 1번 출구 → 나라공원","steps":["긴테쓰나라역 1번 출구에서 노보리오지(登大路)를 따라 동쪽으로 이동.","나라현청·고후쿠지 북쪽을 지나 노보리오지엔치(登大路園地) 부근 나라공원 진입."],"origin":"Kintetsu Nara Station Exit 1","destination":"Nara Park Noborioji Enchi"},
  "d4p4": {"kind":"도보","title":"나라공원 → 도다이지 대불전","steps":["노보리오지엔치에서 동쪽 나라국립박물관 북쪽을 따라 이동.","도다이지 남대문(南大門)을 지나 북쪽 대불전(大仏殿) 매표소로 진입."],"origin":"Nara Park Noborioji Enchi","destination":"Todai-ji Daibutsuden"},
  "d4p5": {"kind":"도보","title":"도다이지 → 긴테쓰나라역 → JR나라역 준비","steps":["대불전에서 남대문으로 내려와 노보리오지 서쪽을 따라 긴테쓰나라역으로 복귀.","지하 코인로커에서 짐을 꺼내고 역 주변에서 빠르게 점심.","공항행 JR을 타려면 긴테쓰나라역에서 JR나라역까지 서쪽으로 약 1.0~1.2km를 더 이동해야 함(다음 카드)."],"origin":"Todai-ji Daibutsuden","destination":"Kintetsu-Nara Station"},
  "d4p6": {"kind":"도보 + JR + 하루카","title":"긴테쓰나라역 → JR나라역 → 덴노지역 → 간사이공항역","steps":["긴테쓰나라역에서 히가시무키 상점가를 남하해 산조도리(三条通)에 합류한 뒤 서쪽 JR나라역 동쪽 출입구까지 이동. 두 나라역은 서로 다른 건물이며 도보 약 15~20분.","JR나라역에서 야마토지선 오사카·덴노지 방면 야마토지쾌속/쾌속 승차 → JR 덴노지역 하차.","JR 덴노지역에서 공항행 특급 하루카(별도 특급권 조건 확인)로 환승 → JR 간사이공항역 종점 하차. 간사이공항 제1터미널은 역 2층 연결 통로 이용."],"tip":"JR 간사이공항역과 난카이 간사이공항역 개찰구를 혼동하지 말 것. 비행편 출발시각·터미널 기준 탑승 전 공항 도착 여유 확보.","origin":"Kintetsu-Nara Station","destination":"Kansai International Airport Terminal 1"}
};

function appendRouteGuide(node,plan){
  const route=ROUTE_DETAILS[plan.id];
  if(!route)return;
  const original=defaults.days.flatMap(d=>d.plans).find(p=>p.id===plan.id);
  const changed=original&&(original.name!==plan.name||original.map!==plan.map);
  const box=document.createElement('details');box.className='route-guide';
  const summary=document.createElement('summary');
  summary.textContent=changed?'이동 경로 참고 · 기존 장소 기준':route.kind+' · '+route.title;
  box.appendChild(summary);
  const list=document.createElement('ol');
  route.steps.forEach(function(step){const li=document.createElement('li');li.textContent=step;list.appendChild(li);});
  box.appendChild(list);
  if(route.tip){const p=document.createElement('p');p.className='route-tip';p.textContent='확인: '+route.tip;box.appendChild(p);}
  const a=document.createElement('a');a.className='route-map';a.target='_blank';a.rel='noopener noreferrer';
  a.href='https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(route.origin)+'&destination='+encodeURIComponent(route.destination)+'&travelmode='+(route.kind.includes('도보')&&!route.kind.includes('전철')&&!route.kind.includes('지하철')&&!route.kind.includes('게이한')?'walking':'transit');
  a.textContent='이 구간 실시간 길찾기 ↗';box.appendChild(a);
  if(changed){const small=document.createElement('small');small.textContent='수정한 일정의 장소·순서에는 원래 경로가 맞지 않을 수 있어요. 현장 출발 전에 재확인하세요.';box.appendChild(small);}
  const walk=node.querySelector('.walking-guide');(walk||node.querySelector('.plan-note')).after(box);
}
